### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by zarcoder** [SZTU-ACM/aqua-toolkit#1] opened 2023-05-16 08:18 UTC
OS: macOS 13.1
pnpm: 8.5.1

pnpm run build

> aqua-toolkit@2.2.4 build /Users/zarcoder/Workspace/aqua-toolkit
> vue-tsc && vite build

src/components/AqI18n.vue:12:25 - error TS7016: Could not find a declaration file for module 'vue-i18n'. '/Users/zarcoder/Workspace/aqua-toolkit/node_modules/.pnpm/registry.npmmirror.com+vue-i18n@9.2.2_vue@3.3.2/node_modules/vue-i18n/dist/vue-i18n.esm-bundler.js' implicitly has an 'any' type.
  There are types at '/Users/zarcoder/Workspace/aqua-toolkit/node_modules/vue-i18n/dist/vue-i18n.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vue-i18n' library may need to update its package.json or typings.

12 import { useI18n } from 'vue-i18n'
                           ~~~~~~~~~~

src/components/AqFileUpload.vue:18:25 - error TS7016: Could not find a declaration file for module 'vue-i18n'. '/Users/zarcoder/Workspace/aqua-toolkit/node_modules/.pnpm/registry.npmmirror.com+vue-i18n@9.2.2_vue@3.3.2/node_modules/vue-i18n/dist/vue-i18n.esm-bundler.js' implicitly has an 'any' type.
  There are types at '/Users/zarcoder/Workspace/aqua-toolkit/node_modules/vue-i18n/dist/vue-i18n.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vue-i18n' library may need to update its package.json or typings.

18 import { useI18n } from 'vue-i18n'
                           ~~~~~~~~~~

src/views/ResolverRank.vue:37:25 - error TS7016: Could not find a declaration file for module 'vue-i18n'. '/Users/zarcoder/Workspace/aqua-toolkit/node_modules/.pnpm/registry.npmmirror.com+vue-i18n@9.2.2_vue@3.3.2/node_modules/vue-i18n/dist/vue-i18n.esm-bundler.js' implicitly has an 'any' type.
  There are types at '/Users/zarcoder/Workspace/aqua-toolkit/node_modules/vue-i18n/dist/vue-i18n.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vue-i18n' library may need to update its package.json or typings.

37 import { useI18n } from 'vue-i18n'
                           ~~~~~~~~~~

src/components/AqPodium.vue:26:25 - error TS7016: Could not find a declaration file for module 'vue-i18n'. '/Users/zarcoder/Workspace/aqua-toolkit/node_modules/.pnpm/registry.npmmirror.com+vue-i18n@9.2.2_vue@3.3.2/node_modules/vue-i18n/dist/vue-i18n.esm-bundler.js' implicitly has an 'any' type.
  There are types at '/Users/zarcoder/Workspace/aqua-toolkit/node_modules/vue-i18n/dist/vue-i18n.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vue-i18n' library may need to update its package.json or typings.

26 import { useI18n } from 'vue-i18n'
                           ~~~~~~~~~~

src/components/AqPodiunList.vue:34:25 - error TS7016: Could not find a declaration file for module 'vue-i18n'. '/Users/zarcoder/Workspace/aqua-toolkit/node_modules/.pnpm/registry.npmmirror.com+vue-i18n@9.2.2_vue@3.3.2/node_modules/vue-i18n/dist/vue-i18n.esm-bundler.js' implicitly has an 'any' type.
  There are types at '/Users/zarcoder/Workspace/aqua-toolkit/node_modules/vue-i18n/dist/vue-i18n.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vue-i18n' library may need to update its package.json or typings.

34 import { useI18n } from 'vue-i18n'
                           ~~~~~~~~~~

src/views/Resolver.vue:144:25 - error TS7016: Could not find a declaration file for module 'vue-i18n'. '/Users/zarcoder/Workspace/aqua-toolkit/node_modules/.pnpm/registry.npmmirror.com+vue-i18n@9.2.2_vue@3.3.2/node_modules/vue-i18n/dist/vue-i18n.esm-bundler.js' implicitly has an 'any' type.
  There are types at '/Users/zarcoder/Workspace/aqua-toolkit/node_modules/vue-i18n/dist/vue-i18n.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vue-i18n' library may need to update its package.json or typings.

144 import { useI18n } from 'vue-i18n'
                            ~~~~~~~~~~

src/views/SeatsGenerator.vue:177:25 - error TS7016: Could not find a declaration file for module 'vue-i18n'. '/Users/zarcoder/Workspace/aqua-toolkit/node_modules/.pnpm/registry.npmmirror.com+vue-i18n@9.2.2_vue@3.3.2/node_modules/vue-i18n/dist/vue-i18n.esm-bundler.js' implicitly has an 'any' type.
  There are types at '/Users/zarcoder/Workspace/aqua-toolkit/node_modules/vue-i18n/dist/vue-i18n.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vue-i18n' library may need to update its package.json or typings.

177 import { useI18n } from 'vue-i18n'
                            ~~~~~~~~~~

src/i18n/index.ts:2:28 - error TS7016: Could not find a declaration file for module 'vue-i18n'. '/Users/zarcoder/Workspace/aqua-toolkit/node_modules/.pnpm/registry.npmmirror.com+vue-i18n@9.2.2_vue@3.3.2/node_modules/vue-i18n/dist/vue-i18n.esm-bundler.js' implicitly has an 'any' type.
  There are types at '/Users/zarcoder/Workspace/aqua-toolkit/node_modules/vue-i18n/dist/vue-i18n.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vue-i18n' library may need to update its package.json or typings.

2 import { createI18n } from 'vue-i18n'
                             ~~~~~~~~~~

Found 8 errors in 8 files.

Errors  Files
     1  src/components/AqI18n.vue:12
     1  src/components/AqFileUpload.vue:18
     1  src/views/ResolverRank.vue:37
     1  src/components/AqPodium.vue:26
     1  src/components/AqPodiunList.vue:34
     1  src/views/Resolver.vue:144
     1  src/views/SeatsGenerator.vue:177
     1  src/i18n/index.ts:2
 ELIFECYCLE  Command failed with exit code 2.

**Comment by SamuNatsu** [comment] 2023-05-16 08:55
This is an error caused by **vue-i18n**.

Its **package.json** file is **broken for typescript**, and it maybe fixed in next vue-i18n version.

You need to fix it manually.

Open `./node_modules/vue-i18n/package.json`

Add `"types": "./dist/vue-i18n.d.ts"` in `/exports/./import`, just like this:
```json
  "exports": {
    ".": {
      "import": {
        "node": "./index.mjs",
        "default": "./dist/vue-i18n.esm-bundler.js",
        "types": "./dist/vue-i18n.d.ts"  <= Here!
      },
      "require": "./index.js"
    },
    "./dist/*": "./dist/*",
    "./index.mjs": "./index.mjs",
    "./package.json": "./package.json"
  }
```

Then rebuild, the problem will be solved

**Comment by Zxilly** [comment] 2023-05-16 14:00
For CI, you should place a patch file in repo. Then apply it in a step before build.

**Comment by SamuNatsu** [comment] 2023-05-16 14:01
Now with the beta version of vue-i18n, type error was fixed, now CI works find here.

**Closed as completed by SamuNatsu** 2023-05-16 14:01 UTC
Labels: bug
